### ISSUE TITLE
Zod schema mismatch from the contracts (missing `.nullable()`)

### ISSUE THREAD

**Issue by PeterMK85** [astahmer/openapi-zod-client#217]
**Describe the bug**

**Minimal reproduction**
[Example](https://openapi-zod-client.vercel.app/?doc=PYBwpgdghiCWBcACAzAOgAyuQKFhAZsPNoogC6xkA2YSAygO5QDmzYATogAphkDOZYOzCIAtIgDy4CAEEuASRQYSiAMbAIZKKrLFSpMAFsosKkhiUwUQwAE%2BTVh1SxgKqrFWQ%2BtFaWiHaRBkQbQALEQAmZX1EAFd2M0QAIlCyMhB4AHpMhlzUGDCwVCFmTPdPCG8%2BTIAZeQBhAFEAOTpG0SjMVMMqJJUANw4%2BFwgkAEYMVDGx7G92QfY%2BPTE4hKQUtJAl7PB%2BQWE0exY2dmdgTItM-uQ%2BkLJQpZVM3eXSEFjdX30tZkeYmPEuy%2BpD4sUMxnYAE8kABVEAAEygZBEUAgiDAAA9YAI8MxEED-oh4WA%2BKp2LAQBQNLCEUiUWjMdiKBA8btEAAjSGIeTw4GIUAcJEjHlIWK05E8Mh84QAR1iJLIACFgPDoXzSMTSeTKSMaYjkYhUeisQJIGR8bxEHhyOFEAIhGB1WoNMjNK9CYaQCBykKNJkAFZ8alOmKk8LGd0e-QAEmE%2BHWAGJMupDCANGbqmGjFBqpK%2BlHSDBvR5fRBMhiepGPVmIyH-rGwPHkkmU2mIBnMjWc5k83Wiz6qWWMaJcgxRIR2IZRPEaBB1MT4VXCV2lx6G02ki3gKn05pM6pw93e1HZbFYMJF%2BR2PLpSS21VV0kIuh0ElVxqSWSKYP6LFVJ4%2BD4fBYioflwHYUs63UTQzXffR%2BxLQcAyDUY61DA9szgwl10TZNtzbDsu1zXh8wLQsvQHEZy0rND9BXWiYhw5s8J3ds907DDjGIshSMJJIABYXzfOtNS-HVqW5CB%2Bigdx4W5AARO0xWLMBeSjAT0H44SyNE7Uf24S0IGAc1CFiCA1I9DSAFZtILXTv11RAADUZNgfURmNTxxIgPlvFUeJKDVKNAV4e1hAAfSgD5QiwlYkgYclkXgXY%2BF4gtxCSYQoEXFK%2BlbXd%2BGWIj3XqOlmCEIL-jISFwCQYB2X9MAdD5EB2AFdgKBJVc3Lg6raqtGCTjrCdjF0AayAANn4utMWsb1AhmKN-B8Mi%2BsCARyRZGaMTmmgkHk4Bfj5CszCdZakFUMqKq%2BAAVFgqzWuqGqaqVCVa9rOr%2BD0errR7xrAIayJGpEkDwSbpqW6wVoLP6NtxY6aMhgIkB%2BL5JSrU9z1U1dxGWp1AVCYzgBhBI%2BD5P76sa5q3ra8DPu6xdfpqwIwYBjhhqEUbQc0Kbtt2hb0DOqHeuZpA4a2sjZtTPaiUO5hYEdKNLuRcqoTgpjNxYgj2KIzJSpViq0piEBCcEEmqC%2BqM-qgdgIMhOsTtihKi2xq8bzIyxDEtmHRbtMhNuYWjHYYxBzvxU3iYSJ0fm9wlrdtqB7bI4OyNIZ2vVd-33YLT3Y7XONcPytj%2BA4w9qju5gjborQyFiPOYlh-34Z0z89MctkBCROuBptEQwsVgtIDBWLxCgaTTCgdkaFokLzOb1PxCDKgLMJKX5vVgvmKLwjOO7RodulsAkhiL59-5qt7O8pAAHIZATrlgHwIkTCoLl9SgfFgDBvhEAAbV-sAaYDyiEMKYdwfAAA0iAAhN1UKIaSVB5QAF0oGoDQVAgBQDQggLAdiKBMDyRwIQcgpBqBEDySRB-OUrlqpWkAvKH%2Bl00SXTriIe4IgCEeEQMQthwAOQiAgCBKgqBr58myvCSgIwZJcFphwemiB8AyW8OTX2Ns7Z8lzqucRkiNDSNkR1BWSwFFKIHnHVR98nSgIgPIZEXskAREsVADENijBGIcVGTRTN%2BqCMMOydmZFBFUCoJPGWWdTEeiyvCCQEBX4o2vOEmIkTomxLdgkxASSYnQlSUAA)

OpenApi:
```yaml
   Example:
      description: 'Array of daily data points [[epoch-millis, metric-value], ..., [epoch-millis, metric-value]]. Data quality issues can cause the metric value to be null.'
      additionalProperties: false
      type: array
      items:
        additionalProperties: false
        type: array
        minItems: 2
        maxItems: 2
        items:
          type: number
          nullable: true
          readOnly: true
        readOnly: true
      readOnly: true
```

Zod:
```ts
const Example = z.array(z.array(z.number()));
```

**Expected behavior**
Zod:
```ts
const Example = z.array(z.array(z.number().nullable()));
```
**Additional context**
It seems the generated type properly reflects the type
```
type Example = Array<Array<number | null>>
```
