### ISSUE TITLE
(maybe) TODO ? provide an option flag to make all properties required by default (rather than the current opposite)

### ISSUE THREAD

**Issue by astahmer** [astahmer/openapi-zod-client#23]
## problem:
currently if a property (in `type: object, properties: { xxx }`) isnt explicitly specified in the `required`, this property will be inferred as optional. this is actually good and the right way / the openapi way of doing things.

sadly, it seems, from my experience at least, that a LOT of APIs openapi spec just forget about this part, so we end up having zod schemas followed by `.partial()` in a lot of places where it's actually not the API's intended behavior.

yes in a perfect world, those APIs definitely SHOULD make proper use of the `required` array and explicitly set every needed property.

## solution:

provide an option `implicitRequired` for `generateZodClientFromOpenAPI`, in `TemplateContext["options"]`, that would infer every properties as required UNLESS a `required` array is actually set

## example:

```yaml
components:
  schemas:
    ExplicitRequired: 
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        tag:
          type: string
      required:
        - id
        - name
    NoRequiredSet: 
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        tag:
          type: string
```

will output something like (using the `implicitRequired` option):
```ts
const ExplicitRequired = z.object({ id: z.string(), name: z.string(), tag: z.string().optional() });
const NoRequiredSet = z.object({ id: z.string(), name: z.string(), tag: z.string() }); // no more `partial.()` here !
```

whereas currently it would output something like:
```ts
const ExplicitRequired = z.object({ id: z.string(), name: z.string(), tag: z.string().optional() });
const NoRequiredSet = z.object({ id: z.string(), name: z.string(), tag: z.string() }).partial();
```
