### ISSUE TITLE
Enum with null value causes type error

### ISSUE THREAD

**Issue by BrandonGoren** [astahmer/openapi-zod-client#236]
**Describe the bug**
As of [1.11.1](https://github.com/astahmer/openapi-zod-client/releases/tag/openapi-zod-client%401.11.1), the following command produces an enum that does not work with zod.

```
openapi-zod-client https://raw.githubusercontent.com/plaid/plaid-openapi/master/2020-09-14.yml -o src/generated/plaid-api-schemas.ts --export-schemas  
```

```
/** Has a type error **/
export const OwnershipType = z.enum([
  null,
  'individual',
  'joint',
  'association',
  'trust',
])
```

**Minimal reproduction**
```
OwnershipType:
    nullable: true
    type: string
    enum:
      - null
      - individual
      - joint
      - association
      - trust
```

**Expected behavior**
The `z.enum` should be nullable, and not include the null value.
