### ISSUE TITLE
Generating a array union when using anyOf

### ISSUE THREAD

**Issue by rushi444** [astahmer/openapi-zod-client#287]
I'm having trouble getting the right types when running the codegen. 

I have some fields in my openapi.yaml that look like this: 
```
        cover_photo_url:
          anyOf:
            - type: string
            - type: 'null'
          title: Cover Photo Url
```

And the outputted type is looking like this: 

```
cover_photo_url?: ((string | null) | Array<string | null>) | undefined
```

Is this expected behavior? Is there a workaround to not have `Array<string | null>` in the output
Or is this something wrong with the way the openapi spec is? This would be out of my control as I'm not responsible for that, thanks!
