### ISSUE TITLE
Issue: Incorrect Zod Schema Generation for `format: date-time` with `oneOf`

### ISSUE THREAD

**Issue by sujanrajs** [astahmer/openapi-zod-client#311]
# Issue: Incorrect Zod Schema Generation for `format: date-time` with `oneOf`

## Summary

When using an OpenAPI schema with `oneOf` to allow either a `date-time` formatted string or an empty string (`""`), the Zod client generator is not correctly converting the `format: date-time` field. Instead, it generates a schema that treats the `date-time` field as a regular string, dropping the `datetime()` validation entirely.

```yml
schema:
   type: object
   properties:
      login:
         oneOf:
            - type: string
              format: date-time  # Should be converted to z.string().datetime()
            - type: string
              enum: [""]         # Allows empty string
```

## Expected Behavior

I was expecting the Zod schema to correctly handle the `date-time` format alongside allowing an empty string. The generated Zod schema should be:

```js
const last_login = z.union([
  z.string().datetime(), // Enforce date-time format
  z.literal("")          // Allow empty string
]);
```

## Result I received
```js
const last_login = z.union([
  z.string(),   // This is a regular string, not a date-time formatted string
  z.literal("") // Empty string is correctly handled
]);
