### ISSUE TITLE
[Question] Inline Enums?

### ISSUE THREAD

**Issue by rmortes** [astahmer/openapi-zod-client#57]
Hi! I've just recently started to work with this library, and I'm loving it so far. I have a question about enums.

I have an endpoint with two GET params: 
```yaml
      - in: query
        name: type
        schema:
          type: string
          enum:
          - One
          - Two
          - Three
      - in: query
        name: o
        schema:
          type: array
          items:
            type: string
            enum:
            - (A - Z)
            - (Z - A)
```

The `type` param comes from a Django model with an enum that gets exported to the schema as well:
```yaml
    TypeEnum:
      enum:
      - ONE
      - TWO
      - THREE
      type: string
```

As you can see, the enum in typed with the DB values, which are all caps, while the values the API will accept are capitalized.
I'm trying to set up a mostly code generated codebase, so I'd love to somehow get `api.thatEndPoint.parameters.type.schema.options`, but AFAIK this is not a trivial matter.

I've been somewhat successful `.find`ing my way around api.api to get to the `type.schema.options`, but this is not typed, so my beautifully typed requests complain of `[string, ...string[]]` not being of type `One | Two | Three`, so this is a no go.

My question is: Is it possible to somehow get the inline enum schema defined in the makeAPi function while retaining typings? And if not, would it be possible to generate and export a zod type for inline enums in the schema?

Thanks!
