### ISSUE TITLE
URL param types

### ISSUE THREAD

**Issue by wongsitu** [astahmer/openapi-zod-client#95]
Hi, the current yaml will generate an api client expecting a  '/pets/:petId' endpoint

```yaml
    /pets/{petId}:
        get:
            summary: Info for a specific pet
            operationId: showPetById
            tags:
                - pets
            parameters:
                - name: petId
                  in: path
                  required: true
                  description: The id of the pet to retrieve
                  schema:
                      type: string
```

Here's the function
```
getPet = (petId: string) => api.get('/pets/:petId', { params: { petId } });
```

The problem when I call `getPet("my-pet-id")` is that it will make a GET request as `/pets/:petId?petId=my-pet-id`. Axios is not going to replace the :petId with the parameter value. I think the solution is that api.get should expect a url of type `/pets/${string}` instead of `/pets/:petId` and without params
